# Generated by Django 5.1 on 2024-12-18 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('fecha_viaje', models.DateField()),
                ('numero_alumnos', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.AlterField(
            model_name='paquete',
            name='destino',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.usuario')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.contrato')),
            ],
        ),
    ]
